---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/doppl-store/current/web
    sys_packages:
      - mcrypt
      - vim
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: apc, package: php-apc }
      - { name: gd, package: php5-gd }
    php_ppa: php5
  roles:
    - init
    - php5-fpm
    - php5-cli
    - php5-common
    - nginx
    - composer
    - phpunit
    - mysql
    - git
    - curl
